# Base image
FROM python:3.12-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y python3-pyqt6 python3-pyqt6.qtsvg python3-pyqt6.qtwebsockets \
                       python3-pip python3-setuptools python3-dev build-essential \
                       net-tools iputils-ping curl xvfb && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy code
COPY pyqt_scanner.py scanner.py requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run GUI app headless with Xvfb
CMD ["sh", "-c", "Xvfb :99 -screen 0 1024x768x16 & python3 pyqt_scanner.py"]
